algoritmo exemplomedia
inicio

real nota1, nota2, media
inteiro taxaFrequencia

escreva("Informe a primeira nota")
leia(nota])
escreva("Informe a segunda nota")
leia(nota2)
escreva("Informe a taxa de frequência")
leia(taxaFrequencia)

media = (nota1 + nota2) /2


se (taxaFrequencia < 75)
    escreva("Reprovado, frequência insuficiente!")
        se(media>= 6)
            escreva("aprovado")
        senao
        escreva("Reprovado, nota insuficiente!")
fim