algoritmo exercicio01
    real deposito, taxa, rendimento, rendimentofinal
    inicio
        escreva("Digite o valor do deposito: ")
        leia(deposito)
        escreva("Digite o valor da taxa de juros do banco: ")
        leia(taxa)
       
        rendimento = deposito * (tava / 100)
        rendimentofinal = deposito + rendimento
       
        escreva("O rendimento é de: " + rendimento + ", então por isso o rendimento Totalizado é " + rendimentofinal)
    fim
 
